"""
TestCase — a single test to run against the target.
Generated by plugins (pure, no network), executed by Executor.
"""
from pydantic import BaseModel
from typing import Optional
from enum import Enum

class TestMode(str, Enum):
    DETECT  = "detect"   # first pass — look for vulnerability
    CONFIRM = "confirm"  # second pass — confirm the finding

class TestCase(BaseModel):
    test_id:         str              # unique id e.g. "xss-001"
    plugin_name:     str              # which plugin generated this
    injection_point: str              # where to inject e.g. "?q="
    target_name:     str              # param/field name being tested
    payload:         str              # actual payload to send
    marker:          Optional[str] = None   # unique nonce to look for in response
    mode:            TestMode = TestMode.DETECT
    require_headless: bool = False
    timeout:         int = 10        # seconds
    retries:         int = 1